name: Update Developer Rankings

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rankings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: List repository contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -R
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run JIRA data extraction
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
        python jira_extract_final.py
        echo "Contents after extraction:"
        ls -R
    - name: Run developer ranking
      run: |
        python dev_ranking_daily.py
        echo "Contents after ranking:"
        ls -R
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add developer_rankings_final.csv
        git commit -m "Update developer rankings" || exit 0
        git push